/**
 * PDF export — captures the results page as a multi-page PDF.
 * Uses html2canvas to rasterize the DOM and jsPDF to assemble pages.
 */

export async function exportResultsToPdf(
  element: HTMLElement,
  filename = "warikoo-health-report.pdf",
): Promise<void> {
  // Dynamic imports — keeps initial bundle lean
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
  ]);

  // Force light theme styles during capture for consistent output
  const wasDark = document.documentElement.classList.contains("dark");
  if (wasDark) document.documentElement.classList.remove("dark");

  // Wait one frame so styles re-apply before capture
  await new Promise((r) => requestAnimationFrame(r));

  let canvas: HTMLCanvasElement;
  try {
    canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      windowWidth: element.scrollWidth,
      logging: false,
    });
  } finally {
    if (wasDark) document.documentElement.classList.add("dark");
  }

  const imgData = canvas.toDataURL("image/jpeg", 0.92);
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pageWidth;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  // Header
  pdf.setFillColor(31, 78, 120);
  pdf.rect(0, 0, pageWidth, 14, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "bold");
  pdf.text("Warikoo Finance Calculator — Health Report", 10, 9);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  const today = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
  pdf.text(today, pageWidth - 10, 9, { align: "right" });

  // Slice the screenshot into A4 pages
  const headerOffset = 16;
  const usablePageHeight = pageHeight - headerOffset - 8;
  let remaining = imgHeight;
  let position = headerOffset;
  let sourceY = 0;

  while (remaining > 0) {
    const sliceHeight = Math.min(remaining, usablePageHeight);
    pdf.addImage(
      imgData,
      "JPEG",
      0,
      position - sourceY,
      imgWidth,
      imgHeight,
      undefined,
      "FAST",
    );

    remaining -= sliceHeight;
    if (remaining > 0) {
      pdf.addPage();
      pdf.setFillColor(31, 78, 120);
      pdf.rect(0, 0, pageWidth, 14, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.text("Warikoo Finance Calculator — Health Report", 10, 9);
      sourceY += sliceHeight;
      position = headerOffset;
    }
  }

  // Footer on last page
  pdf.setTextColor(120, 120, 120);
  pdf.setFontSize(7);
  pdf.text(
    "Generated by Warikoo Calculator — warikoo-calculator.vercel.app | Data stays in your browser.",
    pageWidth / 2,
    pageHeight - 4,
    { align: "center" },
  );

  pdf.save(filename);
}
